on: push
name: Cargo clippy check

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features